/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prueba;

import calculadora.CalculadoraImpuestos; // Importa la librería
import javax.swing.JOptionPane;
/**
 *
 * @author Luis Mario
 */
public class prueba extends javax.swing.JFrame {

    /**
     * Creates new form prueba
     */
    public prueba() {
        initComponents();
        txtTasaIEPS.setText("8.0"); // Valor por defecto para IEPS
        txtTasaISN.setText("3.0");
        txtTasaPredial.setText("0.5");
        txtDescuentoPredial.setText("10.0");
        btnCalcular.setText("Calcular Impuestos"); // Texto más descriptivo
        lblIVA.setText("IVA: $0.00");
        lblISR.setText("ISR: $0.00");
        lblIEPS.setText("IEPS: $0.00");
resetResultados();

    }
    private void resetResultados() {
        lblIVA.setText("IVA: $0.00");
        lblISR.setText("ISR: $0.00");
        lblIEPS.setText("IEPS: $0.00");
       lblISN.setText("ISN: $0.00");
        lblPredial.setText("Predial: $0.00");
        lblISAN.setText("ISAN: $0.00");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonto = new javax.swing.JTextField();
        txtDeducciones = new javax.swing.JTextField();
        txtTasaIEPS = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        lblIVA = new javax.swing.JLabel();
        lblISR = new javax.swing.JLabel();
        lblIEPS = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtTasaISN = new javax.swing.JTextField();
        txtTasaPredial = new javax.swing.JTextField();
        txtDescuentoPredial = new javax.swing.JTextField();
        lblPredial = new javax.swing.JLabel();
        lblISAN = new javax.swing.JLabel();
        lblISN = new javax.swing.JLabel();
        txtNomina = new javax.swing.JTextField();
        txtValorCatastral = new javax.swing.JTextField();
        txtValorVehiculo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 39, 71, -1));
        getContentPane().add(txtDeducciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 73, 71, -1));

        txtTasaIEPS.setText("jTextField3");
        getContentPane().add(txtTasaIEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 113, -1, -1));

        btnCalcular.setText("jButton1");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 30));

        lblIVA.setText("jLabel1");
        getContentPane().add(lblIVA, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        lblISR.setText("jLabel1");
        getContentPane().add(lblISR, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, -1, -1));

        lblIEPS.setText("jLabel1");
        getContentPane().add(lblIEPS, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabel1.setText("Monto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 42, -1, -1));

        jLabel2.setText("IVA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel3.setText("ISR");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        jLabel4.setText("IEPS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        jLabel5.setText("Deducciones");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 76, -1, -1));

        jLabel6.setText("Tasa IEPS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 113, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Calculadora de Impuestos");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 6, -1, -1));

        txtTasaISN.setText("jTextField1");
        getContentPane().add(txtTasaISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 141, -1, -1));

        txtTasaPredial.setText("jTextField1");
        getContentPane().add(txtTasaPredial, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 175, -1, -1));

        txtDescuentoPredial.setText("jTextField1");
        txtDescuentoPredial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescuentoPredialActionPerformed(evt);
            }
        });
        getContentPane().add(txtDescuentoPredial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lblPredial.setText("jLabel8");
        getContentPane().add(lblPredial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        lblISAN.setText("jLabel8");
        getContentPane().add(lblISAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, -1));

        lblISN.setText("jLabel8");
        getContentPane().add(lblISN, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 270, -1, -1));
        getContentPane().add(txtNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 90, -1));
        getContentPane().add(txtValorCatastral, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));
        getContentPane().add(txtValorVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 90, -1));

        jLabel8.setText("Predial");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        jLabel9.setText("ISAN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel10.setText("ISN");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, -1, -1));

        jLabel11.setText("TasaISN");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 144, -1, -1));

        jLabel12.setText("TasaPredial");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel13.setText("Descuento Predial");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel14.setText("Nomina");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, -1, -1));

        jLabel15.setText("ValorCatastral");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, -1, -1));

        jLabel16.setText("Valor Vehicular");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            // Obtener valores de la interfaz
            double monto = Double.parseDouble(txtMonto.getText());
            double deducciones = Double.parseDouble(txtDeducciones.getText());
            double tasaIEPS = Double.parseDouble(txtTasaIEPS.getText());
            double nomina = Double.parseDouble(txtNomina.getText());
            double tasaISN = Double.parseDouble(txtTasaISN.getText());
            double valorCatastral = Double.parseDouble(txtValorCatastral.getText());
            double tasaPredial = Double.parseDouble(txtTasaPredial.getText());
            double descuentoPredial = Double.parseDouble(txtDescuentoPredial.getText());
            double valorVehiculo = Double.parseDouble(txtValorVehiculo.getText());
            
            // Calcular todos los impuestos
            double iva = CalculadoraImpuestos.calcularIVA(monto);
            double isr = CalculadoraImpuestos.calcularISR(monto, deducciones);
            double ieps = CalculadoraImpuestos.calcularIEPS(monto, tasaIEPS);
            double isn = CalculadoraImpuestos.calcularISN(nomina, tasaISN);
            double predial = CalculadoraImpuestos.calcularPredial(valorCatastral, tasaPredial, descuentoPredial);
            double isan = CalculadoraImpuestos.calcularISAN(valorVehiculo);
            
            // Mostrar resultados
            lblIVA.setText(String.format("$%.2f", iva));
            lblISR.setText(String.format("$%.2f", isr));
            lblIEPS.setText(String.format("$%.2f", ieps));
            lblISN.setText(String.format("$%.2f", isn));
            lblPredial.setText(String.format("$%.2f", predial));
            lblISAN.setText(String.format("$%.2f", isan));
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, 
                "ERROR: Todos los campos deben ser números válidos\n"
                + "Ejemplo: 1500.75", 
                "Error de entrada", 
                JOptionPane.ERROR_MESSAGE);
            resetResultados();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, 
                ex.getMessage(), 
                "Error de cálculo", 
                JOptionPane.ERROR_MESSAGE);
            resetResultados();
        }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtDescuentoPredialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescuentoPredialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescuentoPredialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prueba.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new prueba().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblIEPS;
    private javax.swing.JLabel lblISAN;
    private javax.swing.JLabel lblISN;
    private javax.swing.JLabel lblISR;
    private javax.swing.JLabel lblIVA;
    private javax.swing.JLabel lblPredial;
    private javax.swing.JTextField txtDeducciones;
    private javax.swing.JTextField txtDescuentoPredial;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNomina;
    private javax.swing.JTextField txtTasaIEPS;
    private javax.swing.JTextField txtTasaISN;
    private javax.swing.JTextField txtTasaPredial;
    private javax.swing.JTextField txtValorCatastral;
    private javax.swing.JTextField txtValorVehiculo;
    // End of variables declaration//GEN-END:variables
}
